name: Enhancement request
description: Suggest an idea for this project
title: '[Enhancement]: '
labels: [enhancement, cyan]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request!
  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree 
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the enhancement is.
      value: "Describe the enhancement you are proposing in detail. What functionality or feature would you like to see added or improved?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: A clear and concise explanation of why this enhancement would be useful and beneficial.
      value: Explain the use case or scenario where this enhancement would be beneficial. How would it improve the user experience or add value to the tool?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Suggest a solution
      value: If you have specific ideas on how to implement this enhancement, please describe them here. You can include code snippets, algorithm ideas, or any other relevant details.
    validations:
      required: true
  - type: textarea
    id: Additional-Information
    attributes:
      label: Additional Information
      description: Add any other context or information that might be helpful in understanding or evaluating this enhancement suggestion.
      render: shell
